restore:
    restart: always
    build: ./restore
    volumes:
        - restore:/usr/src/app
    ports:
        - "8000:8000"
    command: /usr/local/bin/gunicorn app.wsgi:application -b :8000 --reload
nginx:
    restart: always
    build: ./nginx/
    ports:
        - "80:80"
    volumes_from:
        - restore
    links:
        - restore:api.restore.platypi.dev
